Browser v2
nasa-gcn/gcn.nasa.gov pull request #1052
Opened 2023-06-22 13:16 UTC by dakota002

Removing local dependency on schema repo. Still need to add a means of selecting versions

2023-07-12 18:05 UTC, dakota002 commented
This will require a github api token for the site before merging

2023-07-13 15:35 UTC, lpsinger requested changes

2023-07-13 15:35 UTC, lpsinger commented on app/routes/docs/contributing/index.mdx
> +    # See https://github.com/settings/tokens to generate an api token
```suggestion
    # For parts of the site that pull data using Github's content API (i.e. schema-browser)
    # See https://github.com/settings/tokens to generate an API token
```

2023-07-13 15:35 UTC, lpsinger commented on app/lib/schema-data.ts
> +  return JSON.parse(Buffer.from(ghData.content, 'base64').toString()) as Schema
I'm surprised that it returns the content base64-encoded. Can you avoid the decoding step by setting the [media type](https://github.com/octokit/octokit.js#media-type-formats)?

2023-07-13 15:35 UTC, lpsinger commented on app/routes/docs/schema-browser/$.tsx
> +  if (!path || !path.includes('.schema.json'))
```suggestion
  if (!path?.includes('.schema.json'))
```

2023-07-13 15:35 UTC, lpsinger commented on app/lib/schema-data.ts
> +}
I'm troubled by the performance implications of recursively walking the entire directory tree. It occurs to me that if the schema browser side nav supports expanding _only a single directory at a time_, then we only need to return the listing of a single directory in any one loader invocation.

2023-07-14 20:57 UTC, lpsinger requested changes
Please address the outstanding comments from the last review. Sorry, this is a big PR, it's going to take me a few iterations to spot everything.

2023-07-17 12:36 UTC, dakota002 commented
Still working on the changes from the feedback. The reworking of the getContentTree to not be recursive is just taking a bit longer than I'd like, but should have it done soon

2023-08-02 14:05 UTC, dakota002 commented
Closed by #1130

2023-08-02 14:05 UTC, closed without merging