using light theme to avoid low contrast menu items
nasa-gcn/gcn.nasa.gov pull request #1088
Opened 2023-07-05 14:16 UTC by Courey

<img width="364" alt="Screen Shot 2023-07-05 at 10 15 36 AM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/25cf5c51-0238-465f-a9c9-cf3e652574a1">

This is a quick fix option to avoid the mobile contrast issue in the user navigation menu.

2023-07-05 14:20 UTC, lpsinger commented
I like the idea, but this adversely affects the appearance of the nav when the windows is desktop size:

<img width="1302" alt="Screenshot 2023-07-05 at 10 18 54" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/303f1cb9-99ec-468f-92b7-e6de1cc3d70a">

Is there a straightforward way to have the mobile nav use the light theme and the desktop nav use the dark theme?

2023-07-05 14:20 UTC, Courey commented
yeah, I'm working on seeing if there is a quick fix for that currently. I just wasn't sure you were okay with the mobile menu looking like that.

2023-07-05 14:40 UTC, Courey commented
<img width="1157" alt="Screen Shot 2023-07-05 at 10 36 37 AM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/db3f3e4c-4240-4426-9b2d-a3514416d5f5">
This preserves dark on desktop and light on mobile. The only thing that is not my favorite is if you take the window and shrink it down to mobile size, when it hits 768 pixels wide, you can see the nav bar change colors. I don't know that it's avoidable if we use different styles based on size. 

I'm still seeing if there is an easy quick fix that is a more consistent experience.

2023-07-05 19:30 UTC, lpsinger commented
> This preserves dark on desktop and light on mobile. The only thing that is not my favorite is if you take the window and shrink it down to mobile size, when it hits 768 pixels wide, you can see the nav bar change colors. I don't know that it's avoidable if we use different styles based on size.
> I'm still seeing if there is an easy quick fix that is a more consistent experience.

This has the unwanted side effect of changing the background of the header itself:

![Screenshot 2023-07-05 at 15 26 37](https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/0fdf0389-0953-4d5c-be40-5277e559db3d)

This is all a stopgap measure, right? In the long run, we would like to fix USWDS so that the links in the dark themed mobile nav have high contrast colors, like the white color that is used for nested menus like the "leo.p.singer@nasa.gov +" link in the screen shot below.

![Screenshot 2023-07-05 at 15 28 29](https://github.com/nasa-gcn/gcn.nasa.gov/assets/728407/2174851d-7dcd-41a5-8a5e-e291b096403f)

2023-07-07 12:48 UTC, Courey commented
yes, just a stopgap. This is just to get contrast quickly while I find a better solution. Alternative is waiting till I find that solution to do anything at all. I don't know how much of an issue it has been for users.

2023-07-07 15:03 UTC, Courey commented
<img width="504" alt="Screen Shot 2023-07-07 at 11 00 05 AM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/afd0d855-d8d8-49da-b388-4ce972fa288b">
<img width="625" alt="Screen Shot 2023-07-07 at 11 00 23 AM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/6545874/67b4274f-1711-4416-97ba-897d0ea7e95c">
Here's a better version. it should only impact when not desktop width and preserves highlighting

2023-07-07 17:55 UTC, lpsinger requested changes

2023-07-07 17:55 UTC, lpsinger commented on build/theme/custom.scss
> + * Override user nav text colors to add contrast when not desktop
```suggestion
 * Override user nav text colors to add contrast when not desktop
 * FIXME: remove once https://github.com/bruffridge/nasawds/issues/10 is fixed
```

2023-07-07 18:08 UTC, lpsinger approved these changes

2023-07-07 18:08 UTC, merged