Adds some references to the schema browser
nasa-gcn/gcn.nasa.gov pull request #1591
Opened 2023-10-25 17:45 UTC by dakota002

2023-10-25 17:47 UTC, lpsinger reviewed
Aren't these paths now outdated, given the naming convention changes?

2023-10-26 13:17 UTC, dakota002 commented
@lpsinger I have updated the paths, the should be correct once the schema PR gets merged

2023-10-26 13:23 UTC, lpsinger approved these changes

2023-10-26 13:24 UTC, lpsinger requested changes
Would you please reference the issue that this fixes in the commit message and the PR description so that merging it automatically closes the issue?

2023-10-26 16:01 UTC, lpsinger approved these changes

2023-10-26 16:01 UTC, merged