added note about attachments
nasa-gcn/gcn.nasa.gov pull request #1606
Opened 2023-10-31 14:34 UTC by jracusin

addresses concern raised in support ticket 48

2023-10-31 17:43 UTC, lpsinger requested changes
Please use GitHub Flavored Markdown footnote syntax: https://docs.github.com/en/enterprise-cloud@latest/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes

2023-11-01 13:39 UTC, jracusin commented
I don't like how it puts the footnote all the way at the bottom of the page.  I want users to see it right below the table.  I tried using [!NOTE], but it doesn't render properly, it just prints out "[!NOTE]".

2023-11-01 13:44 UTC, lpsinger commented
> I don't like how it puts the footnote all the way at the bottom of the page. I want users to see it right below the table. I tried using [!NOTE], but it doesn't render properly, it just prints out "[!NOTE]".

OK. This is fine, then.

2023-11-01 13:44 UTC, lpsinger approved these changes

2023-11-01 13:44 UTC, merged