Styling updates to make UI more responsive in the missions pages incl…
nasa-gcn/gcn.nasa.gov pull request #171
Opened 2022-07-18 15:26 UTC by dakota002

…uding word-breaks on links, image scaling, and horizontal scrolling on tables

2022-07-18 16:35 UTC, lpsinger requested changes
What about https://designsystem.digital.gov/components/table/#responsive-stacked-table for the tables?

2022-07-18 16:35 UTC, lpsinger commented on app/routes/missions.tsx
> +      <div className="desktop:grid-col-4 ">
Unnecessary whitespace change.

2022-07-18 16:55 UTC, dakota002 commented
Fixed the whitespace issue, do we want to use those stacked tables? I don't see any immediate benefit, but I am not opposed to using them

2022-07-18 17:24 UTC, dakota002 commented
That's doable, but is there any reason we are keeping these tables as markdown? We will need to define the tables as elements anyway to add the uswds utility class thing. Just thinking the files are looking less and less like markdown. Are you cool with them being turned into tsx files instead? They feel repetitive enough that we might be able to break them into components or something

2022-07-18 17:37 UTC, lpsinger commented
> That's doable, but is there any reason we are keeping these tables as markdown? We will need to define the tables as elements anyway to add the uswds utility class thing. Just thinking the files are looking less and less like markdown. Are you cool with them being turned into tsx files instead? They feel repetitive enough that we might be able to break them into components or something

These particular files are maintained by scientists who can write Markdown but probably are not comfortable with React.

Note that we can globally set all tables in markdown to be responsive by editing the rehype settings in remix.config.js.

2022-07-18 17:51 UTC, dakota002 commented
Ah good to know, in trying that approach I think it makes some of the tables look good, albeit somewhat like nutrition fact labels
![image](https://user-images.githubusercontent.com/11023698/179571779-0c00eeeb-b71b-4550-a3d0-b7a65eb3b6f5.png)
vs 
![image](https://user-images.githubusercontent.com/11023698/179571936-05bcc14c-c6d9-4300-bc6f-cf80bdec1882.png)

But others look a little off, with the empty cells such as this 
![image](https://user-images.githubusercontent.com/11023698/179572149-50d2ff46-8dfe-4c95-a5c1-e8648a79c02a.png)
vs
![image](https://user-images.githubusercontent.com/11023698/179572179-d071b635-4078-4b1d-8aaf-40023f586d45.png)

2022-07-18 18:02 UTC, lpsinger commented
😆 

The ones that look funky, have some colspans and rowspans missing.

2022-07-18 18:05 UTC, dakota002 commented
haha yep playing with some colspans now, is there a rehype-correct way to do colspans?

2022-07-18 20:40 UTC, lpsinger commented
It looks like there is a mix of the two table formats. Is that intended?

<img width="686" alt="Screen Shot 2022-07-18 at 16 39 14" src="https://user-images.githubusercontent.com/728407/179613357-85c89bfe-e21c-48af-b20f-d7a740dd301c.png">

2022-07-19 15:04 UTC, lpsinger commented
Yeah, the tables are all responsive now, but there is something funny going on with the last row of many of the tables. For example:
<img width="608" alt="Screen Shot 2022-07-19 at 11 03 35" src="https://user-images.githubusercontent.com/728407/179783706-297cc591-f99e-48b4-98b7-d52a35968e2b.png">

2022-07-19 19:23 UTC, lpsinger requested changes

2022-07-19 19:23 UTC, lpsinger commented on app/routes/missions/fermi.md
> +| Type | Contents | Latency |
Undo unnecessary whitespace changes here.

2022-07-19 22:32 UTC, lpsinger requested changes

2022-07-20 19:18 UTC, lpsinger approved these changes

2022-07-20 19:18 UTC, merged