New announcements
nasa-gcn/gcn.nasa.gov pull request #1858
Opened 2024-01-23 20:20 UTC by dakota002

resolves #773 

Updated user email notification page:
![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/bc9f7ed7-1df5-4ee0-b936-55e9d71fcf59)

Announcement email form:
![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/29213477-5245-465a-b349-2101f76636d9)

2024-01-24 00:03 UTC, lpsinger requested changes
Remember to configure the action for the unsubscribe link in https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/app/routes/_gcn.unsubscribe.%24jwt/actions.server.ts#L56-L95.

2024-01-24 00:03 UTC, lpsinger commented on app/routes/_gcn.user.email/email_notices.server.ts
> +  ).Items.map((item) => item.email)
You'll definitely have to paginate this. We have enough users that they won't all be returned in a single scan call. See, for example, https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/app/table-streams/circulars/index.ts#L57-L65.

2024-01-24 13:55 UTC, dakota002 commented
@lpsinger where do you think it makes sense to put links to these pages? I don't think there is a direct link to /news, and I don't have one in there yet for the form

2024-01-24 13:59 UTC, dakota002 commented on app/routes/_gcn.user.email/email_notices.server.ts
> +  await sendEmail({
I'm getting this error when I test this, 
```
TypeError: Cannot read properties of undefined (reading 'template')
    at sendEmailBulk (C:\Repos\gcn.nasa.gov\app\lib\email.server.ts:101:39)
```
From the email server:
![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/bb2acce0-dae6-49c7-9653-42626d2112a0)

Are you familiar with how this is defined?

2024-01-24 14:12 UTC, lpsinger commented on app/routes/_gcn.user.email/email_notices.server.ts
> +  await sendEmail({
Yes, it's defined here:

https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/src/plugins/emailOutgoing.js#L50-L57

This won't work in sandbox mode.

2024-01-24 19:19 UTC, lpsinger requested changes

2024-01-24 19:19 UTC, lpsinger commented on app/routes/_gcn.news.email.tsx
> +  return 'OK' //redirect('/news')
How about:

```suggestion
  return null
```

2024-01-24 20:46 UTC, lpsinger requested changes
A better UX for after successful submission may be to show a message saying that the announcement was sent, similar to what we do in the help desk contact form:

https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/app/routes/_gcn.contact.tsx#L98-L117

Sorry for flip-flopping on the pending UI.

2024-01-24 21:07 UTC, dakota002 commented
No worries, I can change that

2024-01-25 14:05 UTC, dakota002 commented
Copied a lot of the formatting from the contact page:

![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/7d5ca9be-1e64-44f2-a283-75b56f5126a8)

2024-01-25 18:26 UTC, dakota002 commented
@lpsinger @jracusin Is this worth including in this PR, a "News" header link:
![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/5daad8f8-0719-4a09-b188-07d7faa3b663)

2024-01-25 19:16 UTC, dakota002 commented
Also a button to link to the announcement page:

![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/11023698/3b3cf4d8-2a74-431c-a6b7-5ed69d0b2bc5)

Is it possible to use a loader or get the user's moderator status in markdown? If not, this button is viewable to anyone, but will take them to an error page if they click it while not signed in

2024-01-25 21:50 UTC, lpsinger commented
> Also a button to link to the announcement page:
> 
> ![image](https://private-user-images.githubusercontent.com/11023698/299782030-3b3cf4d8-2a74-431c-a6b7-5ed69d0b2bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMTk2MTQsIm5iZiI6MTcwNjIxOTMxNCwicGF0aCI6Ii8xMTAyMzY5OC8yOTk3ODIwMzAtM2IzY2Y0ZDgtMmE3NC00MzFjLWE2YjctNWVkNjlkMGIyYmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDIxNDgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZDc1ZjhlMWI2YzMwNmQzN2FmNTNiZjViZGUxY2VjMDBmMGFmZjM2Nzg0NGNkZjQ0MzRkZmNjNTkwY2I4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hp63zVJvCSO9UZQpFZnYAI0SfdVmbR6KHamdqcKe66w)
> 
> Is it possible to use a loader or get the user's moderator status in markdown? If not, this button is viewable to anyone, but will take them to an error page if they click it while not signed in

That's a problem. Yes, you can have a loader in an MDX file.

2024-01-25 22:02 UTC, lpsinger requested changes

2024-01-26 14:07 UTC, dakota002 commented
> > Is it possible to use a loader or get the user's moderator status in markdown? If not, this button is viewable to anyone, but will take them to an error page if they click it while not signed in
> 
> That's a problem. Yes, you can have a loader in an MDX file.

Does it support useLoaderData as well? That would make things a lot easier. How do I implement that?

2024-01-26 15:13 UTC, lpsinger commented
Yup. I don't see why not.

2024-01-26 16:08 UTC, dakota002 commented
Ah okay mdx doesn't really play well with the react hooks, but I was able to break out the button as a component and just make a new hook to use the moderator status, and it works well.

2024-01-29 15:37 UTC, lpsinger requested changes

2024-01-29 15:37 UTC, lpsinger commented on app/routes/_gcn/header/Header.tsx
> +              </NavLink>,
I think that I omitted News from the nav bar because it was too wide. What does this look like on desktop?

2024-01-29 17:21 UTC, lpsinger approved these changes

2024-01-29 17:22 UTC, merged