Hide dropdown content when clicking away
nasa-gcn/gcn.nasa.gov pull request #1989
Opened 2024-02-26 17:16 UTC by tylerbarna

This adds basic functionality to the DetailsDropdownContent component for listening for clicking away from a dropdown, which will cause the dropdown to be hidden from the user unless the dropdown button is pressed again. This will prevent dropdown menus drawing over one another in the circulars archive like so:

![image](https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/2e1fd33b-09c7-443e-aece-46a18fede0c4)

and users won't have to manually hide dropdown menus should they choose to not impose any of the additional search filters.

2024-02-26 17:17 UTC, tylerbarna commented
The current commit seems to interfere with the dropdown button interaction slightly; if the menu is expanded, pressing the button again does not collapse the menu, though clicking anywhere else on the page will collapse the dropdown. This is not the case in the currently deployed commit, so it seems to be due to the implementation made in this PR.

2024-02-26 17:20 UTC, tylerbarna commented
@dakota002 would this affect the use of [DetailsDropdownContent in the schema browser docs](https://github.com/nasa-gcn/gcn.nasa.gov/blob/f657b161c35f3cd92ec2ecfb03f804c2be122b76/app/routes/_gcn.docs_._schema-browser.schema.(%24version).%24/route.tsx#L141)?

2024-02-27 14:47 UTC, dakota002 commented
> @dakota002 would this affect the use of [DetailsDropdownContent in the schema browser docs](https://github.com/nasa-gcn/gcn.nasa.gov/blob/f657b161c35f3cd92ec2ecfb03f804c2be122b76/app/routes/_gcn.docs_._schema-browser.schema.(%24version).%24/route.tsx#L141)?

Without checking, they should work well together, assuming that the property is not required. You should be able to test it out locally though. If you are having issues with the github content on your local let me know

2024-03-25 15:11 UTC, lpsinger requested changes
Please rebase.

Please use the existing hooks [useOnClickOutside](https://usehooks-ts.com/react-hook/use-on-click-outside) or [useClickAnywhere](https://usehooks-ts.com/react-hook/use-click-any-where).

2024-03-25 20:58 UTC, tylerbarna commented
Change to useOnClickOutside changes issue from button not minimizing at all to it minimizing before immediately being expanded again; this is because the DetailsDropdownContent change now detects a click anywhere outside of the actual dropdown content, which then sets the expanded boolean to false, but clicking the button toggles the boolean, resulting in it being set to true again.

2024-03-25 22:23 UTC, lpsinger requested changes

2024-03-25 22:23 UTC, lpsinger commented on app/components/DetailsDropdownContent.tsx
> +    if (onClose) onClose()
```suggestion
    onClose?.()
```

2024-04-01 21:36 UTC, tylerbarna commented
Having some difficulty coming up with an adequately general way of detecting when a user is clicking an element we don't want to trigger the onClose with (eg detecting when the buttons in the buttongroup associated with the popup are clicked). Attempted to use both refs and classnames for this purpose with a check inside DetailsDropdownContent for one of those properties on the event.target, but there's variability in what the identified event.target is depending on where on the segmented button the user clicks

2024-04-09 00:54 UTC, tylerbarna commented
this is not the most eloquent method, but the general idea is present. May be slightly better to use a ref rather than a classname, also some expression that checks all parents/grandparents/etc in the DetailsDropdownContent would be a bit better

2024-04-29 20:23 UTC, lpsinger commented
Did you know that `useOnClickOutside` accepts a list of refs?

```ts
useOnClickOutside([dropdownContentRef, dropdownButtonRef], () => {...})`
```

2024-05-09 21:09 UTC, tylerbarna commented
> Did you know that `useOnClickOutside` accepts a list of refs?
> 
> ```ts
> useOnClickOutside([dropdownContentRef, dropdownButtonRef], () => {...})
> ```

Looking back at our discussion on Monday, did you intend to have the useOnClickOutside defined outside of the DetailsDropdownContent component/have the refs defined in the route.tsx file instead of the DateSelectorMenu and SortSelectorMenu component files?

2024-05-10 12:06 UTC, lpsinger commented
Yes, that would be the simplest.

2024-05-16 13:55 UTC, Courey commented on app/routes/circulars._archive._index/SortSelectorButton.tsx
> +    // const [showContent, setShowContent] = useState(false)
did you mean to delete this?

2024-05-16 13:56 UTC, tylerbarna commented on app/routes/circulars._archive._index/SortSelectorButton.tsx
> +    // const [showContent, setShowContent] = useState(false)
yes i did

2024-05-16 14:00 UTC, Courey commented on app/routes/circulars._archive._index/DateSelectorMenu.tsx
> +                  value=""
is this intentional?

2024-05-16 14:00 UTC, Courey commented on app/routes/circulars._archive._index/DateSelectorMenu.tsx
> +                  value=""
oh I get it, nm.

2024-05-20 20:12 UTC, lpsinger requested changes

2024-05-20 20:12 UTC, lpsinger commented on app/routes/circulars._archive._index/route.tsx
> +  })
These refs and states are only used inside `SortSelector` and `DateSelector`. Please move them inside those two respective components. They need not be exposed as props.

2024-05-21 16:48 UTC, lpsinger requested changes

2024-05-21 16:48 UTC, lpsinger commented on app/routes/circulars._archive._index/DateSelectorMenu.tsx
> +  const [showDateSelector, setShowDateSelector] = useState(false)
Renaming of the state from `showContent` to `showDateSelector` makes this a larger diff than necessary. Please keep the old name.

2024-05-23 14:15 UTC, lpsinger commented on app/routes/circulars._archive._index/DateSelectorMenu.tsx
> +  const dateSelectorRef = useRef<HTMLDivElement>(null)
This is the only ref, so we can just call this variable `ref` without introducing ambiguity.

```suggestion
  const ref = useRef<HTMLDivElement>(null)
```

2024-05-23 14:16 UTC, lpsinger commented on app/routes/circulars._archive._index/SortSelectorButton.tsx
> +  const SortSelectorRef = useRef<HTMLDivElement>(null)
```suggestion
  const ref = useRef<HTMLDivElement>(null)
```

2024-05-24 13:36 UTC, lpsinger approved these changes

2024-05-24 13:36 UTC, merged