Einstein Probe mission page
nasa-gcn/gcn.nasa.gov pull request #2011
Opened 2024-03-01 17:19 UTC by jracusin

This is a start to the EP mission page.  Please provide edits and additional details to include.

2024-03-01 19:10 UTC, lpsinger requested changes

2024-03-01 19:10 UTC, lpsinger commented on app/routes/_gcn.missions.einsteinprobe/logo.png
Is there an SVG version of this image?

2024-03-01 19:12 UTC, lpsinger requested changes
Please fix Prettier issues.

2024-03-01 19:12 UTC, lpsinger commented
@modot, would you please check this?

2024-03-04 15:48 UTC, jracusin commented on app/routes/_gcn.missions.einsteinprobe/logo.png
I have only found a png.

2024-03-04 15:53 UTC, jracusin commented
> Please fix Prettier issues.

done

2024-03-04 18:55 UTC, modot commented
> @modot, would you please check this?

I'll check it in the morning.

2024-03-07 03:14 UTC, modot commented
Hi @jracusin, I just sent an email containing the .svg logos and a patch for the mission page.

2024-03-12 09:39 UTC, jracusin commented
> Hi @jracusin, I just sent an email containing the .svg logos and a patch for the mission page.

I see the email chain, but not the email with the file.  Maybe the attachments were too large that they got blocked.  Could you add them via GitHub?

2024-03-12 09:40 UTC, jracusin commented on app/routes/_gcn.missions.einsteinprobe/route.mdx
> +| WXT        | GRBs, other transients, and non-astrophysical triggers | ??    |
@modot Could you provide information for us to include on rates?

2024-03-25 15:13 UTC, lpsinger commented
Please rebase.

2024-04-01 21:45 UTC, jracusin commented
Rebase had too many conflicts due to change to file structures, so moved this to new PR #2172

2024-04-01 21:45 UTC, closed without merging