Circulars Documentation: Markdown Primer
nasa-gcn/gcn.nasa.gov pull request #2079
Opened 2024-03-12 14:53 UTC by tylerbarna

This PR adds a documentation page that explains markdown and how it can be used when writing new Circulars. Minor updates have also been made to existing documentation pages and components to reference the new page.

This PR resolves #1925

2024-03-14 15:45 UTC, lpsinger commented
Please fix the build failure.

2024-03-15 10:16 UTC, tylerbarna commented
> Please fix the build failure.

yeah sorry, I missed that the useFeature import was removed in another commit when I merged the upstream commits

2024-03-15 12:19 UTC, jracusin commented
Can you please add some screenshots of the documentation?  It'll be easier to see how this all gets rendered that way.

2024-03-15 12:20 UTC, jracusin commented
There also needs to be some explanation of how this interfaces to the automated linking and recognition of URLs that's already in place.

2024-03-16 16:55 UTC, tylerbarna commented
> Can you please add some screenshots of the documentation? It'll be easier to see how this all gets rendered that way.

sure, here's the current version:
<img width="984" alt="image" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/555e25e0-d10d-4de4-bb68-81e53eff57b2">
<img width="986" alt="image" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/ca40c298-4010-4df4-bc30-3e817b1e5267">
<img width="983" alt="image" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/053c6e0a-a8b9-4ba7-ac5a-c1a44801cf49">
<img width="980" alt="image" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/bccf440c-e959-48bd-87fc-88db49a748c3">
<img width="981" alt="image" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/3ce052ac-f699-40ac-acd9-d298ea524df5">
<img width="982" alt="image" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/57914086/bfd9e0aa-5ef3-45b4-b327-05af69f7eeda">

2024-03-18 22:58 UTC, lpsinger commented
> This PR solves #1925

Remember to use [GitHub's keywords for automatically closing issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue).

2024-03-18 23:09 UTC, lpsinger requested changes
Would you please add some introductory text explaining what Markdown is, and linking to the first-party Markdown primer?

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +    <td>This is \*\*Bold\*\*</td>
Please use inline code formatting for inline syntax examples.

```suggestion
    <td>`This is **Bold**`</td>
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +      \-/\*/+ Item 1<br></br>\-/\*/+ Item 2<br></br>\-/\*/+ Item 3
Please use block code formatting for block syntax examples.

```suggestion
      ```
      - Item 1
      * Item 2
      + Item 3
      ```
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +{SyntaxReference()}
```suggestion
<SyntaxReference/>
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +Header levels 1 and 2 can be created using an alternate method; the first and second levels of header is created by following the header text with a line of `=` or `-` symbols, respectively.
Avoid passive voice.

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +Tables can be created in markdown by using the `|` symbol to separate columns and `-` symbols to separate the header from the body. The first row of the table is the header, and the second row is the
Markdown is a proper noun.

```suggestion
Tables can be created in Markdown by using the `|` symbol to separate columns and `-` symbols to separate the header from the body. The first row of the table is the header, and the second row is the separator. The rest of the rows are the body of the table.
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +
Remove unnecessary heading. The preceding section has no content.

```suggestion
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +  breadcrumb: Markdown
```suggestion
  breadcrumb: Astro Flavored Markdown
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +# Astro-Flavored Markdown
```suggestion
# Astro Flavored Markdown
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +### Basic Text Formatting
Decrease levels of section headings.

```suggestion
## Basic Text Formatting
```

2024-03-18 23:09 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +Markdown formatting can be accessed in the quick menu of the markdown bar, but it can also be added manually.
This is not sufficiently descriptive of where to find this in the user interface.

2024-03-19 11:40 UTC, tylerbarna commented
> > This PR solves #1925
> 
> Remember to use [GitHub's keywords for automatically closing issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue).

oops, forgot 'solves' wasn't in the list. Thanks!

2024-03-19 14:46 UTC, tylerbarna commented
It seems that the prettier checks are failing due to the block code syntax used in the block code examples

2024-03-22 14:47 UTC, lpsinger commented
Please rebase.

2024-03-25 18:30 UTC, lpsinger requested changes
Please fix build failures.

2024-03-25 18:41 UTC, lpsinger requested changes

2024-03-25 18:41 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
Rename this file to app/routes/docs.circulars.markdown.mdx.

2024-03-25 18:47 UTC, lpsinger requested changes

2024-03-25 18:47 UTC, lpsinger commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +    <td># Header 1</td>
```suggestion
    <td>`# Header 1`</td>
```

...and same for the rest of the rows

2024-03-25 19:25 UTC, tylerbarna commented on app/routes/_gcn.docs.circulars.markdown.mdx
> +<table class="usa-table">
I added some styling to the Table components to make them more in line with what's used for the SyntaxReference

2024-03-25 22:11 UTC, lpsinger approved these changes

2024-03-25 22:11 UTC, lpsinger commented
Nice, thank you!

2024-03-25 22:12 UTC, merged