BurstCube Mission page
nasa-gcn/gcn.nasa.gov pull request #2152
Opened 2024-03-29 17:12 UTC by jracusin

![GCN - Missions - BurstCube](https://github.com/nasa-gcn/gcn.nasa.gov/assets/5199538/ac593ca4-078e-4627-915c-5122fb8d3508)

2024-03-29 17:16 UTC, jracusin commented
Addresses issue #2045

2024-03-29 18:58 UTC, aam97 approved these changes

2024-03-31 17:41 UTC, lpsinger requested changes

2024-03-31 17:41 UTC, lpsinger commented on app/routes/missions.burstcube/logo.png
Would you please provide any SVG version of this image?

2024-03-31 17:41 UTC, lpsinger commented on app/routes/missions.burstcube/route.mdx
> +| BurstCube   | 50-1000 keV  | 6 ster        | ~30° radius (statistical, 90% confidence) |
```suggestion
| BurstCube   | 50-1000 keV  | 6 sr          | ~30° radius (statistical, 90% confidence) |
```

2024-03-31 17:41 UTC, lpsinger commented on app/routes/missions.burstcube/route.mdx
> +| `Alert` (update) | Localization HEALPix map | 15 minutes |
```suggestion
| `Alert` (update) | Localization HEALPix map | 15 min     |
```

2024-03-31 17:41 UTC, lpsinger commented on app/routes/missions.tsx
It looks like you rearranged the order of the missions. Would you please do that in a separate PR?

2024-04-01 14:08 UTC, jracusin commented on app/routes/missions.burstcube/logo.png
We do not have a SVG version of the image, only a PDF, and I've tried to convert to SVG, but have only come up with a very distorted version. If you have a good way to convert, I can send you the pdf.

2024-04-01 14:42 UTC, jracusin commented on app/routes/missions.tsx
See #2166

2024-04-12 19:40 UTC, dakota002 approved these changes

2024-04-12 19:42 UTC, merged

2024-04-15 00:37 UTC, lpsinger commented
Note that this added some broken links because we don't yet have a release of the schema that includes BurstCube.