add Einstein Probe mission page
nasa-gcn/gcn.nasa.gov pull request #2172
Opened 2024-04-01 21:45 UTC by jracusin

![GCN - Missions - Einstein Probe](https://github.com/nasa-gcn/gcn.nasa.gov/assets/5199538/da1d932e-c4de-45f2-9606-38dfb1be4557)

2024-04-02 03:15 UTC, Vidushi-GitHub commented
[@modot](https://github.com/modot) This PR is for EP mission page, which was discussed earlier as well. Could you provide information for us to include on latency?

2024-04-02 03:22 UTC, modot commented on app/routes/missions.einsteinprobe/route.mdx
> +| `gcn.notices.einstein_probe.wxt.alert` | Localization, Count Rate, Significance | TBD     |
Latency should be ~1 min

2024-04-02 03:23 UTC, modot commented on app/routes/missions.einsteinprobe/route.mdx
> +| WXT        | GRBs, other transients, and non-astrophysical triggers | TBD   |
Rates should be ~100

2024-04-02 03:24 UTC, modot commented on app/routes/missions.einsteinprobe/route.mdx
> +| Wide Field X-ray Telescope | 0.5 – 5 keV  | 3600 deg<sup>2</sup> | 5 arcmin (FWHM)        |
Energy Range should be 0.5 - 4 keV
Localization should be 2 arcmin (FWHM)

2024-04-02 15:54 UTC, modot requested changes
Please see the comments I made recently.

2024-04-10 22:01 UTC, Vidushi-GitHub commented on app/routes/missions.einsteinprobe/route.mdx
> +| Wide Field X-ray Telescope | 0.5 – 5 keV  | 3600 deg<sup>2</sup> | 5 arcmin (FWHM)        |
```suggestion
| Wide Field X-ray Telescope | 0.5 - 4 keV  | 3600 deg<sup>2</sup> | 2 arcmin (FWHM)        |
```

2024-04-10 22:03 UTC, Vidushi-GitHub commented on app/routes/missions.einsteinprobe/route.mdx
> +| `gcn.notices.einstein_probe.wxt.alert` | Localization, Count Rate, Significance | TBD     |
```suggestion
| `gcn.notices.einstein_probe.wxt.alert` | Localization, Count Rate, Significance | ~1 min    |
```

2024-04-10 22:04 UTC, Vidushi-GitHub commented on app/routes/missions.einsteinprobe/route.mdx
> +| WXT        | GRBs, other transients, and non-astrophysical triggers | TBD   |
```suggestion
| WXT        | GRBs, other transients, and non-astrophysical triggers | ~100   |
```

2024-04-11 05:25 UTC, Vidushi-GitHub commented
@modot  Could you please confirm the final modifications? see the screenshot of mission page:
<img width="864" alt="Screenshot 2024-04-11 at 1 23 51 AM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/103223246/46c0c38c-f632-4661-9fe6-91d09e6a55d5">

2024-04-11 05:26 UTC, Vidushi-GitHub approved these changes

2024-04-11 05:35 UTC, modot commented
@Vidushi-GitHub Could you please remove `(FWHM)` for the WXT localization in the first sheet? `2 arcmin` is sufficient.

2024-04-11 05:37 UTC, Vidushi-GitHub commented on app/routes/missions.einsteinprobe/route.mdx
> +| Wide Field X-ray Telescope | 0.5 - 4 keV  | 3600 deg<sup>2</sup> | 2 arcmin (FWHM)        |
```suggestion
| Wide Field X-ray Telescope | 0.5 - 4 keV  | 3600 deg<sup>2</sup> | 2 arcmin        |
```
@modot done!

2024-04-11 05:39 UTC, Vidushi-GitHub commented
> @Vidushi-GitHub Could you please remove `(FWHM)` for the WXT localization in the first sheet? `2 arcmin` is sufficient.

@modot Corrected! Any other suggestion?

2024-04-11 05:53 UTC, modot commented
@Vidushi-GitHub All good now. Thanks!

2024-04-11 07:36 UTC, modot approved these changes
All good. Thanks!

2024-04-11 17:49 UTC, Vidushi-GitHub commented
@jracusin and @lpsinger all feedbacks from the team has been implemented, shall we merge it?

2024-04-11 18:07 UTC, lpsinger requested changes

2024-04-11 18:07 UTC, lpsinger commented on app/routes/missions.einsteinprobe/logo.png
Please obtain an SVG version of this image.

2024-04-11 20:29 UTC, Vidushi-GitHub commented
@modot Please attach the SVG image of the EP logo here (at GitHub). Thanks

2024-04-12 20:57 UTC, Vidushi-GitHub commented on app/routes/missions.einsteinprobe/route.mdx
> +import logo from './logo.png'
```suggestion
import logo from './logo.svg'
```

2024-04-12 21:07 UTC, Vidushi-GitHub commented
@jracusin EP mission page is almost done. 

Things needed for your branch:
-git pull this branch for updating the changes in your branch
-Please remove logo.png, as logo.svg is added
-Rebase and merge

2024-04-15 16:18 UTC, jracusin commented
@Vidushi-GitHub This branch has been rebased.

2024-04-15 16:34 UTC, Vidushi-GitHub commented
@modot, @jracusin and @lpsinger, Kindly approve the final changes. 
<img width="990" alt="Screenshot 2024-04-15 at 12 30 47 PM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/103223246/188a2fce-eff0-456d-8056-b32adf44153b">

2024-04-15 16:46 UTC, modot approved these changes
Great! Thanks a lot for all the effort!

2024-04-15 17:59 UTC, Vidushi-GitHub approved these changes

2024-04-15 20:08 UTC, merged