SVOM mission page
nasa-gcn/gcn.nasa.gov pull request #2175
Opened 2024-04-02 20:31 UTC by Vidushi-GitHub

SVOM logo needs to be requested by Team.

<img width="730" alt="Screenshot 2024-04-02 at 4 29 01 PM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/103223246/2b1a1ce6-6993-4bb4-92ad-0e2a743d1f30">

2024-04-08 13:47 UTC, lpsinger requested changes

2024-04-08 13:47 UTC, lpsinger commented on app/routes/missions.svom/route.mdx
> +# Space Variable Objects Monitor
```suggestion
# Space Variable Objects Monitor (SVOM)
```

2024-04-08 17:49 UTC, Vidushi-GitHub commented on app/routes/missions.svom/route.mdx
> +example [JSON ECLAIRs message](gcn/notices/svom/eclairs/alert.slewing.example.json) and [JSON GRM message](gcn/notices/svom/grm/alert.grm.example.json) files are available to use. See the [Schema Bro
Ok thanks, I will check again.

2024-04-08 17:56 UTC, Vidushi-GitHub commented on app/routes/missions.svom/route.mdx
> +SVOM distributes alerts and localizations detections of gamma-ray transients. These notices are published on the GCN Kafka topic `gcn.notices.svom`.
Yes, you are right.

2024-04-10 21:59 UTC, Vidushi-GitHub commented on app/routes/missions.svom/route.mdx
> +example [JSON ECLAIRs message](gcn/notices/svom/eclairs/alert.slewing.example.json) and [JSON GRM message](gcn/notices/svom/grm/alert.grm.example.json) files are available to use. See the [Schema Bro
Link should work after merge of https://github.com/nasa-gcn/gcn-schema/pull/126/files

2024-04-11 18:25 UTC, lpsinger commented on app/routes/missions.svom/route.mdx
> +example [JSON ECLAIRs message](gcn/notices/svom/eclairs/alert.slewing.example.json) and [JSON GRM message](gcn/notices/svom/grm/alert.grm.example.json) files are available to use. See the [Schema Bro
No, it will work after merging that PR _and doing a release_. So this is blocked by https://github.com/nasa-gcn/gcn-schema/pull/126.

2024-04-11 18:36 UTC, Vidushi-GitHub commented on app/routes/missions.svom/route.mdx
> +example [JSON ECLAIRs message](gcn/notices/svom/eclairs/alert.slewing.example.json) and [JSON GRM message](gcn/notices/svom/grm/alert.grm.example.json) files are available to use. See the [Schema Bro
Oh! I will email them. Some corrections need to be made by them.

2024-04-11 20:49 UTC, Vidushi-GitHub commented
@lpsinger For EP, the schema and browser links are not provided, thus, I have updated SVOM one accordingly. Is this ok?

<img width="858" alt="Screenshot 2024-04-11 at 4 46 19 PM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/103223246/df596109-72eb-4baa-80ac-a5594234c716">

2024-07-30 19:25 UTC, Vidushi-GitHub commented
It's pretty stale branch with lots of merge conflict. As mission team is looking into it, created a new PR #2499

2024-07-30 19:25 UTC, closed without merging