BurstCube Note
nasa-gcn/gcn.nasa.gov pull request #2293
Opened 2024-05-21 21:24 UTC by Vidushi-GitHub

# Description
USWSD note for BurstCube

`Resolves #2275`

2024-05-22 01:06 UTC, lpsinger requested changes

2024-05-22 01:06 UTC, lpsinger commented on app/routes/missions.burstcube/route.mdx
> +} from '@trussworks/react-uswds'
Remove unused imports.

```suggestion
import { SummaryBox } from '@trussworks/react-uswds'
```

2024-05-22 01:26 UTC, lpsinger requested changes

2024-05-22 01:26 UTC, lpsinger commented on app/routes/missions.burstcube/route.mdx
> +</SummaryBox>
I think that an Alert would work better here.

2024-05-23 02:44 UTC, lpsinger requested changes

2024-05-23 02:44 UTC, lpsinger commented on app/routes/missions.burstcube/route.mdx
> +<Alert type="info" heading="Information" headingLevel="h4">
"Information" is an unusual choice for heading. Consider the following instead:

```suggestion
<Alert type="warning" heading="Not yet active" headingLevel="h4">
```

2024-05-23 13:26 UTC, Vidushi-GitHub commented
<img width="874" alt="Screenshot 2024-05-23 at 9 26 04 AM" src="https://github.com/nasa-gcn/gcn.nasa.gov/assets/103223246/1cbdcd71-c416-4a30-8250-3f87fabb4b57">

2024-05-23 14:08 UTC, lpsinger approved these changes

2024-05-23 14:09 UTC, merged