SVOM Mission Page
nasa-gcn/gcn.nasa.gov pull request #2499
Opened 2024-07-30 19:22 UTC by Vidushi-GitHub

# Description
PR for adding SVOM mission page over GCN website.
 
SVOM team feedback and .svg logo is requested.

# Related Issue(s)

Closing #2175 , as had 200+ merge conflicts.
https://github.com/Vidushi-GitHub/gcn.nasa.gov/pull/3 is also implemented @https://github.com/timroland

2024-07-30 19:27 UTC, Vidushi-GitHub commented
Attached Mission Page 
<img width="683" alt="Screenshot 2024-07-30 at 2 26 21 PM" src="https://github.com/user-attachments/assets/f354338c-53f9-473e-babb-22f23d5c7ab8">

2024-08-01 16:35 UTC, lpsinger reviewed
Why is this a work in progress?

2024-08-01 18:54 UTC, jracusin commented on app/routes/missions.svom/route.mdx
> +|                                    | Red Band: 650 - 1000 nm |               |                                                |
This needs to also have the VT details, or be on the same row in the table as the blue info.

2024-08-01 18:55 UTC, jracusin commented on app/routes/missions.svom/route.mdx
> +| Gamma Ray Monitor | GRBs, and other transients (TBD) | TBD          |
(TBD) not needed if it says "and other transients)

Use either full names or acronyms, not a combination, so "Gamma ray Monitor" should be "GRM"

2024-08-01 19:50 UTC, Vidushi-GitHub commented on app/routes/missions.svom/route.mdx
> +|                                    | Red Band: 650 - 1000 nm |               |                                                |
```suggestion
| Visual Telescope (VT)                               | Red Band: 650 - 1000 nm |  26' x 26'              |     ~TBD'' radius (statistical, 90% confidence)                                       |
```

2024-08-01 19:51 UTC, Vidushi-GitHub commented on app/routes/missions.svom/route.mdx
> +| Visual Telescope (VT)                               | Red Band: 650 - 1000 nm |  26' x 26'              |     ~TBD'' radius (statistical, 90% confidence)                                       |
```suggestion
| Visual Telescope (VT)                | Red Band: 650 - 1000 nm |  26' x 26'              |  ~TBD'' radius (statistical, 90% confidence)                                       |
```

2024-09-03 17:00 UTC, Vidushi-GitHub commented on app/routes/missions.svom/route.mdx
> +| Microchannel X-ray Telescope (MXT) | 15 - 5000 keV           | 1.1° x 1.1°   | ~10-100'' radius (statistical, 90% confidence) |
@timroland please provide the feedback for correct energy range of MXT.

2024-10-13 17:55 UTC, Vidushi-GitHub commented
<img width="809" alt="Screenshot 2024-10-13 at 23 25 04" src="https://github.com/user-attachments/assets/a52c8ad7-0567-4346-8777-cbdb2e557333">
<img width="844" alt="Screenshot 2024-10-13 at 23 25 13" src="https://github.com/user-attachments/assets/4bfd1df6-eed7-42bc-ad25-c7598bf6dfb5">

@timroland could you please check the content/

2024-10-15 02:40 UTC, lpsinger requested changes
This PR touches lots of unrelated files. This looks like an incomplete rebase attempt.

2024-10-15 07:41 UTC, Vidushi-GitHub commented
> This PR touches lots of unrelated files. This looks like an incomplete rebase attempt.

Yes, I din't squash properly. Shall I close this and make a fresh PR or rebase again?

2024-10-15 23:06 UTC, lpsinger commented
> > This PR touches lots of unrelated files. This looks like an incomplete rebase attempt.
> 
> Yes, I din't squash properly. Shall I close this and make a fresh PR or rebase again?

Whatever you know how to do and are comfortable with.

2024-10-21 14:49 UTC, Vidushi-GitHub commented
#2637 PR is opened.

2024-10-21 14:49 UTC, closed without merging