Circulars - Lucene search documentation
nasa-gcn/gcn.nasa.gov pull request #2502
Opened 2024-07-30 20:51 UTC by tylerbarna

# Description
This adds basic documentation for the Lucene search, hidden behind a feature flag.

# Related Issue(s)

#2288, #2501 

# Testing
1. Add `CIRCULARS_LUCENE` feature flag to `.env` 
2. Navigate directly to http://localhost:3333/docs/circulars/lucene
3. Read Documentation

1. Remove `CIRCULARS_LUCENE` feature flag from `.env` 
2. Navigate directly to http://localhost:3333/docs/circulars/lucene
3. Page should not load

2024-08-01 16:34 UTC, lpsinger requested changes
Please take a look at https://ui.adsabs.harvard.edu/help/search/search-syntax for some ideas for how to structure this documentation page.

On the search page itself, I'd like to have a one-page quick reference (could be a modal or a disclosure section expanded by clicking a button) that is similar to the examples on ADS:
<img width="1421" alt="Screenshot 2024-08-01 at 12 33 53" src="https://github.com/user-attachments/assets/ff999264-0d59-44bb-bce9-7f7c49e88743">

2024-08-01 16:47 UTC, tylerbarna commented
> Please take a look at https://ui.adsabs.harvard.edu/help/search/search-syntax for some ideas for how to structure this documentation page.
> 
> On the search page itself, I'd like to have a one-page quick reference (could be a modal or a disclosure section expanded by clicking a button) that is similar to the examples on ADS: <img alt="Screenshot 2024-08-01 at 12 33 53" width="1421" src="https://private-user-images.githubusercontent.com/728407/354306199-ff999264-0d59-44bb-bce9-7f7c49e88743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzExMDAsIm5iZiI6MTcyMjUzMDgwMCwicGF0aCI6Ii83Mjg0MDcvMzU0MzA2MTk5LWZmOTk5MjY0LTBkNTktNDRiYi1iY2U5LTdmN2M0OWU4ODc0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxNjQ2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTZjYjM2OTczZjBmNTUzZDc3Y2NmNWE2YjUyMTMwYTcwZDA4MTQwMmJmZGE2NTc2OTU5ZGQ3NWE3ZDM2YjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lYAtdy-OdQ3PZM0VluneF3yTaB9x34Ojz5faSbgR0BY">

I agree on the point regarding modal quick selection; I was planning on implementing that in a separate PR

2024-08-01 16:48 UTC, tylerbarna commented
Adding filtering by date range as part of the lucene syntax would likely be a separate PR as well to ensure it ties in with the existing feature correctly

2024-09-30 15:34 UTC, lpsinger requested changes
This looks great, but can we title the page "Advanced Search"?

2024-09-30 15:34 UTC, lpsinger commented on app/routes/docs.circulars.lucene.mdx
> +- Submitter: `submitter`
```suggestion
The following fields are supported: `subject`, `body`, and `submitter`.
```

2024-10-08 12:44 UTC, lpsinger requested changes
- Make "Swift" title case instead of all caps.
- Add a hyperlink to this page from the side nav.

2024-10-08 20:41 UTC, tylerbarna commented on app/routes/docs.circulars.lucene.mdx
> +Searches can be performed by specifying the field and search term. The syntax for this is `field:"search term"`. For example, to search for circulars with the word 'SWIFT' in the subject field, the q
ah, apologies, thought I had corrected this prior to [7816af5](https://github.com/nasa-gcn/gcn.nasa.gov/pull/2502/commits/7816af51014e99bab078f0b065c4b29dc2609960)

2024-10-09 11:14 UTC, lpsinger approved these changes

2024-10-09 11:14 UTC, merged