Circulars - Add Documentation for the Circulars Archive
nasa-gcn/gcn.nasa.gov pull request #2503
Opened 2024-07-31 16:25 UTC by tylerbarna

# Description
this adds basic search documentation for the current search paradigm. This does not make reference to lucene queries, which are still hidden behind a feature flag.

# Related Issue(s)
Resolves #2501 

# Testing
1. Navigate to http://localhost:3333/docs/circulars/archive
2. There should be a new section called "Searching the Archive"

2024-08-01 15:40 UTC, dakota002 approved these changes

2024-08-01 20:00 UTC, lpsinger requested changes
- No need to mention the migration here.
- No need to mention OpenSearch; that's an architecture detail that is not important for users.
- Please use the pronoun "you" to refer to the user to match the style of the rest of this document.
- Rephrase without using directions like "right" or "left" as these adjective may have no meaning for accessible modalities such as screen readers.

2024-08-02 16:48 UTC, lpsinger requested changes
In several places you have many words where one will do. For example:

`The Circulars archive includes a search functionality to enable you to find specific Circulars via keyword.` -> `You can search the Circulars archive by keyword.`

`This is accomplished selecting the dropdown button labeled "Filter by date".` -> `Select the dropdown button labeled "Filter by date".`

Please rephrase these two paragraphs in the plainest possible language.

2024-08-02 21:22 UTC, lpsinger requested changes

2024-08-02 21:22 UTC, lpsinger commented on app/routes/docs.circulars.archive.mdx
> +You can search the Circulars Archive by keyword. This search tool indexes the subject, body, and submitter of all Circulars. Upon initiating a query, the search tool will return all Circulars that ma
```suggestion
You can search the Circulars Archive by keywords or phrases in the subject, body, and submitter fields. By default, results will be returned in reverse chronological order, but you can also choose to sort the results by relevance. You can navigate through the search results using pagination controls and specify the number of results to display per page. By default, 100 results are displayed per page.
```

2024-08-02 21:22 UTC, lpsinger commented on app/routes/docs.circulars.archive.mdx
> +Additionally, you can filter search results by the date of their submission. Select the dropdown button labeled "Filter by date". From there, you can either select from a number of predefined time ra
```suggestion
You can also filter search results by submission date. Select the dropdown button labeled "Filter by date". From there, you can either select from a number of predefined time ranges (e.g., "Last Hour", "Last Day", etc.) or specify a custom date range, which can either be set as a start date, an end date, or both. All search filters can be cleared by clicking the 'x' button in the search bar.
```

2024-08-07 21:19 UTC, lpsinger approved these changes

2024-08-07 21:19 UTC, merged