Moves the definition of the send function to resolve issues with kafka related imports in the remix build
nasa-gcn/gcn.nasa.gov pull request #2590
Opened 2024-09-20 18:36 UTC by dakota002

Resolves #2588

Still in testing

It looks like the issue started with [this commit](https://github.com/nasa-gcn/gcn.nasa.gov/commit/dd4f9d6971c3e35e1d6c46fe69180f4affeacc4b)

This PR moves the definition of the send function so it can still be reusable

2024-09-20 18:55 UTC, lpsinger commented
This won't fix the issue. The problem is that the zstd shared library is not getting bundled.

2024-09-20 19:38 UTC, dakota002 commented
> This won't fix the issue. The problem is that the zstd shared library is not getting bundled.

I'm investigating this as an option for the first possible solution you mentioned. 
"Ensure that it is always the table stream Lambda that is sending Kafka records"

The table-stream lambda already is the only thing sending Kafka records. But, since it was exporting a function that gets used in the remix lambda, I'm trying to determine whether or not that meant that its dependencies are getting tangled up in an unintended way. 

The main issue that I am seeing though is that this may be suggesting the problem is also going to be present in https://github.com/nasa-gcn/gcn.nasa.gov/pull/2301

Still investigating though, I think the better solution will be to figure out the inclusion of the lib, but in the meantime this may be a good option to unblock the broken deployments

2024-09-21 00:57 UTC, lpsinger commented
> I'm investigating this as an option for the first possible solution you mentioned.

I understand now. Go for it!

2024-09-24 10:00 UTC, lpsinger reviewed
How will this fix the issue?

2024-09-24 14:05 UTC, dakota002 commented
> How will this fix the issue?

I linked the commit that caused this in the description at the top. Specifically I believe that exporting/importing the `send` function from  `app/table-streams/circulars/index.ts` caused the dependencies (the zstd node lib required by gcn-kafka) to be required by the main build. 

Moving the send function out should resolve the issue, since this will be back, more or less, to a successful build state

2024-09-24 14:58 UTC, dakota002 commented
I'm pretty sure that's not the case though, where are you referring to? The only place I see our Kafka send function used is in the table-stream

2024-09-24 15:12 UTC, lpsinger commented
> I'm pretty sure that's not the case though, where are you referring to? The only place I see our Kafka send function used is in the table-stream

Right, I understand now. OK, this will work!

2024-09-24 15:14 UTC, lpsinger requested changes

2024-09-24 15:14 UTC, lpsinger commented on app/lib/email.server.ts
The file `email.server.ts` contains functions for sending any kind of email. Nothing in this file now is specific to GCN Circulars. Please put the Circulars specific methods somewhere else.

2024-09-24 15:42 UTC, dakota002 commented on app/lib/email.server.ts
Good point, I moved them to the circulars server in the latest commit

2024-09-24 15:55 UTC, lpsinger requested changes

2024-09-24 15:55 UTC, lpsinger commented on app/lib/email.server.ts
Are the remaining changes to this file still necessary?

2024-09-24 17:17 UTC, dakota002 commented on app/lib/email.server.ts
nope! Reverted in latest commit

2024-09-25 07:32 UTC, lpsinger approved these changes

2024-09-25 07:34 UTC, merged