New Producer Issue Template
nasa-gcn/gcn.nasa.gov pull request #2627
Opened 2024-10-15 17:45 UTC by jracusin

# Description
Creating new issue template for onboarding new notice types, so that we have a streamlined procedure. Each individual step should be its own PR.

# Related Issue(s)
Replaces nasa-gcn/.github/#19

# Testing

2024-10-15 18:34 UTC, dakota002 approved these changes

2024-10-15 23:06 UTC, lpsinger requested changes

2024-10-15 23:06 UTC, lpsinger commented on .github/ISSUE_TEMPLATE/producer-onboarding.md
> +name: Onboarding New Producer
```suggestion
name: Add New GCN Notice Producer
```

2024-10-15 23:06 UTC, lpsinger commented on .github/ISSUE_TEMPLATE/producer-onboarding.md
> +about: Steps to add new producer notices
```suggestion
about: Checklist to add a new producer of GCN Notices
```

2024-10-17 21:22 UTC, lpsinger approved these changes

2024-10-17 21:22 UTC, merged