adds initial km3net notice and mission page link
nasa-gcn/gcn.nasa.gov pull request #2629
Opened 2024-10-15 20:44 UTC by dakota002

Mission page does not yet exist

Needs confirmation of listed topics to be added

2024-11-06 20:21 UTC, Vidushi-GitHub approved these changes

2024-11-22 13:12 UTC, lpsinger requested changes

2024-11-22 13:12 UTC, lpsinger commented on app/components/NoticeTypeCheckboxes/NoticeTypeCheckboxes.tsx
> +  if (useFeature('KM3NET_QUICKSTART')) {
Could we call the feature flag:

```suggestion
  if (useFeature('KM3NET')) {
```

2024-11-22 14:04 UTC, lpsinger approved these changes

2024-11-22 14:13 UTC, merged