Circulars: Add In-Page Lucene Documentation
nasa-gcn/gcn.nasa.gov pull request #2713
Opened 2024-11-12 19:24 UTC by tylerbarna

# Description
This adds a brief explanation of Lucene queries to the Circulars Archive page, hidden behind a feature flag. 

![image](https://github.com/user-attachments/assets/bd0187f8-a526-460b-ba3c-0adabb8b273f)

Note: This is a simplified version of #2589 that removes the quick action buttons until the proper implementation can be identified.
# Related Issue(s)
Tracked by https://github.com/nasa-gcn/gcn.nasa.gov/issues/2288

# Testing
1. Navigate to Circulars Archive
2. Click on the "Advanced Search" (Tentative Label) Accordion Menu
3. The menu should expand

2024-11-22 18:24 UTC, lpsinger reviewed
This is now short enough that I don't know if it needs a disclosure arrow. Can you incorporate it into the existing help text there?

2024-11-25 18:30 UTC, lpsinger commented
> > This is now short enough that I don't know if it needs a disclosure arrow. Can you incorporate it into the existing help text there?
> 
> I was under the impression we would integrate the quick actions as a separate PR once we figured the proper method out; would we not want to retain the disclosure menu for when those are added?

I suggested that you make the examples non-clickable, not that you remove them entirely. If we remove the entirely, then there's no need for the additional disclosure section.

I would rather that you add them back, but make them non-interactive.

2024-12-08 19:38 UTC, tylerbarna commented
> > > This is now short enough that I don't know if it needs a disclosure arrow. Can you incorporate it into the existing help text there?
> > 
> > 
> > I was under the impression we would integrate the quick actions as a separate PR once we figured the proper method out; would we not want to retain the disclosure menu for when those are added?
> 
> I suggested that you make the examples non-clickable, not that you remove them entirely. If we remove the entirely, then there's no need for the additional disclosure section.
> 
> I would rather that you add them back, but make them non-interactive.

Ah, apologies for the misunderstanding. I'll add them back without making them interactive

2024-12-08 20:21 UTC, tylerbarna commented
@lpsinger I added the examples back; they're still clickable, but I've made it so clicking them copies the example to the clipboard. Would that be useful, or would it be better to make them unclickable?

2024-12-08 21:11 UTC, lpsinger requested changes
This is a nice touch, but if you want to support copying the text to the clipboard, please reuse the existing components and look-and-feel that we have for that:

![Screenshot 2024-12-08 at 16 08 16](https://github.com/user-attachments/assets/81b773a9-5668-481c-adab-5fae0364f618)

This is a block-level component. If you need an inline component, there is https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/app/components/CopyableCode.tsx, although it doesn't have the tooltip status. (@dakota002, if Tyler decides to use that, please refactor CopyableCode and Highlight so that they both consistently use the nice tooltip you added. If not, let's delete CopyableCode, because it is unused.)

Note on appearance: it is jarring that the font size and color does not match the existing help text there.

2024-12-08 21:11 UTC, lpsinger commented on app/routes/circulars._archive._index/LuceneMenu.tsx
> +        <Link className="usa-link" to="/docs/circulars/lucene">
This link is broken.

2024-12-08 21:11 UTC, lpsinger commented on app/routes/circulars._archive._index/LuceneMenu.tsx
> +          Lucene Search Syntax Page
Poor link text: every link goes to a "page", so "page" is redundant.

2024-12-08 21:11 UTC, lpsinger commented on app/routes/circulars._archive._index/LuceneMenu.tsx
> +      <div>
Unnecessary div.

2024-12-08 21:11 UTC, lpsinger commented on app/routes/circulars._archive._index/LuceneMenu.tsx
Add copyright banner.

2024-12-16 16:40 UTC, tylerbarna commented
not sure what's going on with the playwright check

2025-01-08 14:39 UTC, dakota002 commented
@tylerbarna The tests can be a bit flaky, I reran it and they passed

2025-01-08 15:08 UTC, dakota002 approved these changes

2025-01-17 17:30 UTC, tylerbarna commented
This is how the Highlight component implementation looks
<img width="992" alt="Screenshot 2025-01-17 at 12 27 21" src="https://github.com/user-attachments/assets/7ddf7a72-92f4-4ad6-8b83-6f06f818fe36" />

2025-01-17 17:47 UTC, dakota002 approved these changes

2025-01-17 18:02 UTC, merged