DO NOT MERGE
nasa-gcn/gcn.nasa.gov pull request #2736
Opened 2024-11-26 17:42 UTC by Courey

DO NOT MERGE. Please put approval in comment. ticket will be closed once approved.

2025-02-18 21:42 UTC, lpsinger requested changes

2025-02-18 21:42 UTC, lpsinger commented on app/backfill-eventId.js
> +// running as a node script it would not import the module from the file
I'm not comfortable copying and pasting this. If you are not able to import it from a standalone Node.js script, then please convert this to a `.ts` source and use esbuild to compile it down to JS. You should be able to hack something into https://github.com/nasa-gcn/gcn.nasa.gov/blob/main/esbuild.config.js to do that.

2025-02-18 21:42 UTC, lpsinger commented on app/backfill-eventId.js
> +        })
This is quite complicated. I would be more comfortable with the correctness of a functional programming implementation using [TC39 Async Iterator Helpers](https://github.com/tc39/proposal-async-iterator-helpers) (see polyfills [available from core-js](https://github.com/zloirock/core-js?tab=readme-ov-file#asynciterator-helpers)).

2025-02-20 14:39 UTC, Courey commented
I wish these major changes had been requested when I first asked for in depth review _before_ I started running out of test data. I can still run this script on test, there is still data there to test on, but I am totally out of data pertaining to the synonym slug backfill, all that is left is production data. This will bloat the time for this ticket.

2025-02-20 17:54 UTC, Courey commented on app/backfill-eventId.js
> +// running as a node script it would not import the module from the file
can you explain to me why? It's a literal cut and paste (though I will have to adapt the GRB matcher to include ones without a letter). Copying and pasting directly from the current app code and updating that subject matcher shouldn't be an issue. I'm not sure what compiling etc would buy us over a copy and paste. I also have the issue that I need to include eventIds on circulars that have GRBs without a letter, but they are not permissible anymore, so it shouldn't be added to the app subject matchers. I'm not sure what hacking around in the esbuild would get us that would be any better

2025-02-20 18:43 UTC, jracusin commented on app/backfill-eventId.js
> +// running as a node script it would not import the module from the file
This script is standalone and will only be run once on prod.  It also requires changes compared to the regular subject matchers to account for changes in GRB naming over time.  If there are no problems with the logic of how this is being implemented, let's just go with how this is currently implemented.

2025-02-20 18:50 UTC, lpsinger commented on app/backfill-eventId.js
> +// running as a node script it would not import the module from the file
> can you explain to me why? It's a literal cut and paste (though I will have to adapt the GRB matcher to include ones without a letter). Copying and pasting directly from the current app code and updating that subject matcher shouldn't be an issue. I'm not sure what compiling etc would buy us over a copy and paste. I also have the issue that I need to include eventIds on circulars that have GRBs without a letter, but they are not permissible anymore, so it shouldn't be added to the app subject matchers. I'm not sure what hacking around in the esbuild would get us that would be any better

For the same reasons why we try to avoid duplicate copies of all but the simplest code in general: there is the risk that the two copies will not be the same, that bugs in one won't be fixed in the other, that they will become incompatible, etc. Even though this PR contains code that we do not plan to reuse, there is still the very real risk that the new copy in the PR will not be the same as the original copy in the main source code.

We have added new regular expressions several times while this PR has been open. In order to review this properly, one would need to manually check that the two copies are the same in this PR, and then we would need to re-check it any time one makes changes to either this PR or to the original code on the main branch.

I do not think that this is an acceptable risk, but @jracusin should have the final say.

2025-02-20 20:33 UTC, Courey commented on app/backfill-eventId.js
> +// running as a node script it would not import the module from the file
I think it's fine. I can just check the subject matchers before I run them. I have both in my current version. I also have to adapt the GRB matcher so it includes GRBs without a letter in them. Currently the subject matchers will only match on GRBs with a letter. So there is already going to be a difference than what would be imported.

2025-02-20 21:44 UTC, lpsinger commented on app/backfill-eventId.js
> +        })
There are a lot of loops and conditionals here, which makes the code too complicated to review quickly.

As for whether we have existing code like this, I don't know of any other examples where we have a paginated input, which is filtered, and then which must be paginated again for insertion. That is the source of the complexity.

2025-02-28 15:50 UTC, lpsinger commented on app/backfill-eventId.js
> +// running as a node script it would not import the module from the file
Here's how to modify the esbuild script to build out the additional script.

```
diff --git a/esbuild.config.js b/esbuild.config.js
index 463a36ae..6130b007 100644
--- a/esbuild.config.js
+++ b/esbuild.config.js
@@ -7,7 +7,7 @@ import { basename, dirname, join } from 'path'
 const args = process.argv.slice(2)
 const dev = args.includes('--dev')
 const entryPoints = await glob(
-  './app/{email-incoming,scheduled,table-streams}/*/index.ts'
+  './app/{email-incoming,scheduled,table-streams,migrations}/*/index.ts'
 )
 
 /**
@@ -19,8 +19,9 @@ const options = {
   logLevel: 'info',
   outdir: 'build',
   outbase: 'app',
-  outExtension: { '.js': '.cjs' },
+  outExtension: { '.js': '.mjs' },
   external: ['@aws-sdk/*', 'aws-sdk'],
+  format: "esm",
   platform: 'node',
   target: ['node20'],
   minify: !dev,
```

Then put your script in `app/migrations/event-id/index.ts`, run `npm run build:esbuild`, and then execute the script by running `node build/migrations/event-id/index.mjs`.

2025-02-28 15:51 UTC, lpsinger commented on app/backfill-eventId.js
> +        })
So, the core-js polyfills would work just fine, but they won't be necessary if we make the following changes:

- Overwrite all event IDs, regardless of whether or not they are already populated.
- Process all events at once. No need to do it in small batches spread over days.

I discussed both of these changes with @jracusin, and she agrees.

2025-04-08 15:04 UTC, closed without merging