DO NOT MERGE
nasa-gcn/gcn.nasa.gov pull request #2785
Opened 2024-12-13 17:44 UTC by Courey

DO NOT MERGE!!! for review only

2024-12-16 02:20 UTC, lpsinger requested changes

2024-12-16 02:20 UTC, lpsinger commented on app/backfill-synonym-slugs.ts
> +}
You could use [lodash's chunk](https://lodash.com/docs/4.17.15) here.

2024-12-16 02:20 UTC, lpsinger commented on app/backfill-synonym-slugs.ts
> +  const TableName = db.name('synonyms')
Architect's service discovery will not work in this context. You'll need to look up the name of the table using Amazon SSM.

2025-02-10 21:56 UTC, lpsinger requested changes

2025-02-10 21:56 UTC, lpsinger commented on app/backfill-synonym-slugs.js
> +}
This is probably correct, but I'd use [lodash's `chunk`](https://lodash.com/docs/#chunk).

2025-02-10 21:56 UTC, lpsinger commented on app/backfill-synonym-slugs.js
> +  const ssmClient = new SSMClient({ region: 'us-east-1' })
You shouldn't have to explicitly specify the region.

```suggestion
  const ssmClient = new SSMClient()
```

2025-02-10 21:56 UTC, lpsinger commented on app/backfill-synonym-slugs.js
> +  const client = new DynamoDBClient({ region: 'us-east-1' })
Again, you shouldn't have to specify the region explicitly.

2025-02-18 21:00 UTC, Courey commented
so I tried it without the region and it doesn't work without a region. Just for future reference. I added it back in and was able to run things fine.

2025-02-18 21:15 UTC, lpsinger commented
> so I tried it without the region and it doesn't work without a region. Just for future reference. I added it back in and was able to run things fine.

Interesting. I think I have `AWS_REGION` set in my environment; maybe that made a difference. Not important, though.

2025-02-18 21:19 UTC, lpsinger commented on app/backfill-synonym-slugs.js
> +  }
FWIW, you could safely remove this entire `try`/`except` block. You'll get a good stack trace either way.

2025-02-18 21:19 UTC, lpsinger commented on app/backfill-synonym-slugs.js
> +  console.log('Starting SYNONYM SLUG backfill... ', startTime)
Consider [`console.time`](https://developer.mozilla.org/en-US/docs/Web/API/console/time_static) and [`console.timeEnd`](https://developer.mozilla.org/en-US/docs/Web/API/console/timeEnd_static).

2025-02-20 14:57 UTC, Courey commented
There is no more test data to test this script. The only env left with data is prod.

2025-02-20 21:48 UTC, lpsinger commented
> There is no more test data to test this script. The only env left with data is prod.

OK, what's your new test strategy? If we could only ever test this once, then perhaps we did not have an adequate test strategy.

2025-04-08 15:04 UTC, closed without merging