Adds a function to parse events from subject lines
nasa-gcn/gcn.nasa.gov pull request #663
Opened 2023-03-08 19:55 UTC by dakota002

2023-03-08 20:03 UTC, lpsinger requested changes
- The match should only be at the beginning of the subject line.
- We should not only capture the object name, but also attempt to normalize it somewhat to a a common format. For example, both `GRB123456A` and `GRB 123456A` should map to `GRB 123456A`.
- We need some unit tests! I'll add Jest so you can do that.

2023-03-09 18:22 UTC, dakota002 commented on app/routes/circulars/circulars.lib.ts
> +    'Baksan\\sNeutrino\\sObservatory\\sAlert[.\\s|_|-]*\\d{6}.\\d{2}',
Cool cool, I will opt for 1 in the next commit

2023-03-09 18:31 UTC, lpsinger requested changes

2023-03-09 18:31 UTC, lpsinger commented on app/routes/circulars/circulars.lib.ts
> +export function parseEventFromSubject(value: string): string {
TS should be able to infer the return type OK for this function:

```suggestion
export function parseEventFromSubject(value: string) {
```

2023-03-09 20:18 UTC, lpsinger requested changes

2023-03-09 20:18 UTC, lpsinger commented on app/routes/circulars/circulars.lib.ts
> +  ]
Move to module scope, so that we don't redefine all of these anonymous functions on every invocation.

2023-03-09 20:18 UTC, lpsinger commented on app/routes/circulars/circulars.lib.ts
> +  }
First search for a match of any of the regexes at the _beginning_ of the string. Then search for a match of any of the regexes _anywhere_ in the string.

2023-03-09 20:18 UTC, lpsinger commented on app/routes/circulars/circulars.lib.ts
> +    [/GRB[.\s|_|-]*(\d{6}[a-zA-Z|.]\d*)/, ([, id]) => `GRB ${id}`],
In the delimiter part of the pattern, `[.\s|_|-]*`, does the `.` match any character? Or does it match a literal period?

Also: how about we do case-insensitive matching with the regexp `i` flag? That will make the parser a bit more forgiving, and also will eliminate the need to have `[a-zA-Z]`.

2023-03-09 20:49 UTC, lpsinger requested changes

2023-03-09 20:49 UTC, lpsinger commented on app/routes/circulars/circulars.lib.ts
> +  }
Split into two loops: we prefer _any_ match at the beginning of the string to _any_ match later in the string.

2023-03-09 20:49 UTC, lpsinger commented on app/routes/circulars/circulars.lib.ts
> +  ],
Normalize the case of all of these matches. For example:

```ts
...
[/LIGO\/Virgo[.\s_-]*S(\d{6}[a-z]+)/i, ([, id]) => `LIGO/Virgo S${id.toLowerCase()}`],
...
```

2023-03-10 16:45 UTC, lpsinger approved these changes

2023-03-10 16:45 UTC, lpsinger commented
@jracusin, would you please review this as well?

2023-03-10 21:47 UTC, jracusin commented
GCN Circ [33451](https://gcn.gsfc.nasa.gov/gcn3/33451.gcn3) Trigger 1159327: Swift detection of SGR1806-20 is another confusing case as the event is SGR 1806-20, but the subject focuses on the trigger.

2023-03-10 21:49 UTC, lpsinger commented
> GCN Classic handled this correctly.

Did it? Or did Scott or Teresa fix it?

2023-03-10 21:51 UTC, jracusin commented
This was submitted today, so it was automated.

2023-03-10 21:53 UTC, lpsinger commented
> This was submitted today, so it was automated.

OK, so @dakota002, would you add a unit test for that please?

2023-03-10 21:55 UTC, jracusin commented
> > This was submitted today, so it was automated.
> 
> OK, so @dakota002, would you add a unit test for that please?

But if it's not the first time the source was detected, and clearly not for this one, and you parse the string "SGR1806-20", is it actually okay?  Though note the missing space.

2023-03-13 20:33 UTC, jracusin approved these changes

2023-03-14 04:48 UTC, merged