Missions - updated text for Fermi, Swift, LVK
nasa-gcn/gcn.nasa.gov pull request #86
Opened 2022-06-02 15:57 UTC by eburnsastro

Minor changes, additional table each for Fermi, Swift LVK. Commits from June 2nd on should be the only ones that matter (I pulled from the main fork/repo yesterday).

2022-06-02 17:54 UTC, lpsinger requested changes

2022-06-02 17:54 UTC, lpsinger commented on app/routes/missions/swift.md
> +Trigger Rates determined from catalogued information including the [Swift-BAT Third GRB Catalog](https://swift.gsfc.nasa.gov/results/batgrbcat/index.html) and the [Swift GRB Lookup Table](https://swi
Switch to the more common American English spelling:

```suggestion
Trigger Rates determined from cataloged information including the [Swift-BAT Third GRB Catalog](https://swift.gsfc.nasa.gov/results/batgrbcat/index.html) and the [Swift GRB Lookup Table](https://swift.gsfc.nasa.gov/archive/grb_table/). GUANO results are from the [online summary table](https://www.swift.psu.edu/guano/).
```

2022-06-02 17:54 UTC, lpsinger commented on app/routes/missions/swift.md
> +| `SWIFT_BAT`  | 8-10      | 2-4        | GUANO arcminute recovery rate |
No need to typeset instrument names in `monospace` as if they were code.

Also, use en dashes (–, option+dash on macOS) for numerical ranges.

```suggestion
| BAT | 70–80     | 7–9        | On-board trigger rate         |
| XRT  | 60–65     | 40–50      | XRT follow-up detections      |
| UVOT | 20–25     | 0–1        | UVOT follow-up detections     |
| `SWIFT_BAT`  | 8–10      | 2–4        | GUANO arcminute recovery rate |
```

2022-06-02 17:54 UTC, lpsinger commented on app/routes/missions/fermi.md
> +| `FERMI_LAT` | `GRB`                            | 15-20 |
```suggestion
| Instrument  | Type                             | Rates |
| ----------- | -------------------------------- | ----- |
| GBM | Short GRB                      | 35–40 |
|             | Long GRB                       | 200   |
|             | Soft Gamma-ray Repeater Flares | 35–40 |
|             | Terrestrial Gamma-ray Flashes  | 80–90 |
|             | Solar Flares                   | 90–95 |
| LAT | GRB                            | 15–20 |
```

2022-06-03 03:27 UTC, lpsinger requested changes

2022-06-03 03:27 UTC, lpsinger commented on app/routes/missions/lvk.md
> +| `Binary Black Hole`       | 79 (35–168)                       | 41 (35–48)             |
No need to set in teletype/monospace font here:

```suggestion
| Binary Neutron Star       | 10 (0–62)                         | 33 (28–38)             |
| Neutron Star-Black Hole   | 1 (0–92)                          | 50 (42–58)             |
| Binary Black Hole         | 79 (35–168)                       | 41 (35–48)             |
```

2022-06-03 14:36 UTC, lpsinger commented
@eburnsastro, I've approved this, but GitHub won't let me merge it because there are conflicts. Would you please resolve the merge conflicts?

2022-06-03 15:03 UTC, eburnsastro commented
> 

@lpsinger I do not see merge conflicts. Nothing appears on this page and pulling from the tachgsfc/gcn.nasa.gov main did not identify any. I pulled this and pushed back here but still see nothing. If you let me know how to see the merge conflict (Google only brought the previous options) I can work on fixing it

2022-06-03 15:40 UTC, lpsinger commented
Hmm, it still says that there are merge conflicts.

2022-06-03 15:56 UTC, eburnsastro commented
I see this when attempting to find merge conflicts:
(base) eburns@heimdall:~/tach/my_fork/gcn.nasa.gov$ git checkout missions
Switched to branch 'missions'
(base) eburns@heimdall:~/tach/my_fork/gcn.nasa.gov$ git fetch upstream
(base) eburns@heimdall:~/tach/my_fork/gcn.nasa.gov$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
(base) eburns@heimdall:~/tach/my_fork/gcn.nasa.gov$ git merge upstream/main
Already up to date.
(base) eburns@heimdall:~/tach/my_fork/gcn.nasa.gov$ git push origin missions
Everything up-to-date

Suggestions?

2022-06-03 17:22 UTC, merged

2022-06-03 17:22 UTC, lpsinger commented
I rebased it by hand and merged it. Thanks!