Updates all but c sample to include offset in print statements
nasa-gcn/gcn.nasa.gov pull request #941
Opened 2023-05-19 15:55 UTC by dakota002

@lpsinger do you have ideas on how to add the same bit to the c code sample?

2023-05-19 18:33 UTC, lpsinger commented
> @lpsinger do you have ideas on how to add the same bit to the c code sample?

Sure. I'll make a PR to add it to your branch.

2023-05-19 18:34 UTC, lpsinger requested changes
Let's be explicit in the formatting of the message:

```
topic={topic} offset={offset}
```

2023-05-19 18:40 UTC, dakota002 commented
Good call, I can update that after your change

2023-05-19 20:00 UTC, lpsinger requested changes

2023-05-19 20:00 UTC, lpsinger commented on app/components/ClientSampleCode.tsx
> +                console.log(\`topic = \${payload.topic} offset = \${payload.message.offset}\`)
```suggestion
                console.log(\`topic=\${payload.topic}, offset=\${payload.message.offset}\`)
```

2023-05-19 20:00 UTC, lpsinger commented on app/components/ClientSampleCode.tsx
> +                  Console.WriteLine( string.Format("topic = {0} offset = {1}",consumeResult.Topic, consumeResult.Offset));
```suggestion
                  Console.WriteLine(string.Format("topic={0}, offset={1}",consumeResult.Topic, consumeResult.Offset));
```

2023-05-19 20:01 UTC, lpsinger commented
Have you run all of these code samples to test them, @dakota002?

2023-05-19 20:47 UTC, lpsinger commented
@dakota002, here's the C language version: https://github.com/dakota002/gcn.nasa.gov/pull/202

2023-05-21 18:28 UTC, dakota002 commented
@lpsinger yep, I ran them to make sure I was using the correct methods for each language sample

2023-05-21 19:10 UTC, lpsinger approved these changes

2023-05-21 19:10 UTC, merged